feat(standards): update to comply with new c++ standards
As per https://docs.unrealengine.com/5.0/en-US/MigrationGuide/ updating from Native Pointers to TObjectPtr's. Without this change, errors like `Error: Native pointer usage in member declaration detected [[[AALSBaseCharacter*]]].  This is disallowed for the target/module, consider TObjectPtr as an alternative.` will occur if compiled outside of a path containing `/plugins/`. So if a user migrates to their own project source folder, or once Epic fixes up the TODO in https://github.com/EpicGames/UnrealEngine/blob/5.0.0-preview-1/Engine/Source/Programs/UnrealHeaderTool/Private/HeaderParser.cpp#L4144-L4152 to remove the current exclusion, users will face compilation errors. This commit future proof's this.